import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import { useMantineColorScheme, ActionIcon, rem } from "@mantine/core";
import { useTheme } from "~/contexts/Theme";

import { Flex, Stack, Text } from "@mantine/core";

const Home: NextPage = () => {
  // eslint-disable-next-line @typescript-eslint/unbound-method
  const { toggleColorScheme } = useMantineColorScheme();
  const { isDark } = useTheme();

  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div>
        <Stack>
          <div>START</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>

          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
          <div>content</div>
        </Stack>
      </div>
    </>
  );
};

export default Home;
